version: "3"

services:
  webserver:
    image: nanorocks/webserver-1:latest
    container_name: 'devbox-webserver1'
    restart: 'no'
    ports:
      - "8080:80"
    links: 
      - mysql
    volumes: 
      - ./docker/apache/:/etc/apache2/sites-available/
      - ./web:/var/www/
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: 'devbox-mysql1'
    restart: 'no'
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: devbox
      MYSQL_DATABASE: tubeDb
      MYSQL_USER: devbox
      MYSQL_PASSWORD: devbox